### ISSUE TITLE
Refetch work

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#192] opened 2017-09-08 19:23 UTC
Check the test, make sure it's working.

**Comment by aappling-usgs** [comment] 2017-09-08 19:59
this could be a bandaid on the way to fully implementing #102, or a complement to that future work.

specific example: we want a block like this to not run each time:
```  -
    id: precip-data
    fetcher: precip
    start.date: "2017-09-07"
    end.date: "2017-09-08"
    scripts: scripts/fetch/fetchPrecip.R
    location: cache/precip.csv
    mimetype: text/csv
    refetch: FALSE
    depends:
      counties: counties
    comment: disabling refetch to avoid too many GDP requests
```
and yet it seems to be running each time

**Comment by aappling-usgs** [comment] 2017-09-12 15:12
at first, refetch=TRUE was supposed to mean don't ever cache this
then later we thought refetch=FALSE was supposed to mean don't ever refetch this
clearly communication will need to be part of this solution

**Comment by aappling-usgs** [comment] 2017-09-12 16:24
here's what refetch claims to do right now (https://github.com/USGS-VIZLAB/vizlab/blob/0.2.x/vignettes/vizlabExample.Rmd#controlling-the-fetch-section):
> By default, the refetch option is set to TRUE in the viz.yaml for each section. vizlab checks the timestamps of online resources to see if the file or resource has changed since it was last fetched. If the timestamp has changed, or a timestamp cannot be obtained, the data will be fetched again. However, this may be undesireable in some scenarios. To force vizlab to use the cached versions of remote files, set refetch to FALSE in the relevant sections of the viz.yaml. Conversely, to force vizlab to refetch the data regardless of timestamps, set refetch to TRUE and delete the timestamps for each section. These are stored in vizlab/make/timestamps.

**Comment by aappling-usgs** [comment] 2017-09-12 16:36
experience in irma (quotes & summaries from slack)

1. how does one get a block like this to not run each time (because it still is):
```
  -
    id: precip-data
    fetcher: precip
    start.date: "2017-09-07"
    end.date: "2017-09-08"
    scripts: scripts/fetch/fetchPrecip.R
    location: cache/precip.csv
    mimetype: text/csv
    refetch: FALSE
    depends:
      counties: counties
    comment: disabling refetch to avoid too many GDP requests
```

2. "it was always a bit goofy I think", "I don't think it has ever worked as expected"

3. people forget that refetch=TRUE (e.g., they had it at FALSE but then pull as TRUE, don't notice) and then get frustrated that it's refetching

4. the way that folks are coding re-fetch in functions doesn't work well, since it doesn't end up fetching the first time.
e.g.
```
if(viz[["refetch"]]){
   do stuff
} else {
   return(NULL)
}
```

5. if you have it set to false and you code in the check like that, the target doesn't built when you change the code

**Comment by aappling-usgs** [comment] 2017-09-12 18:14
The implementation of `refetch` appears to be simply a renaming of `fetchTimestamp` to `refetch`, nothing more: https://github.com/USGS-VIZLAB/vizlab/pull/59/files

**Comment by aappling-usgs** [comment] 2017-09-12 20:30
with `refetch: FALSE`:
```make
iris-data: data/iris.csv
data/iris.csv: 
	export R_LIBS_USER=$(RLIBSUSER);\
	${RBATCH} "--args fun=fetch funargs=list(viz='iris-data')" \
	vizlab/make/callFunction.R vizlab/make/log/fetch/iris-data.Rout
```

with `refetch: TRUE`:
```make
iris-data: data/iris.csv
data/iris.csv: vizlab/make/timestamps/iris-data
	export R_LIBS_USER=$(RLIBSUSER);\
	${RBATCH} "--args fun=fetch funargs=list(viz='iris-data')" \
	vizlab/make/callFunction.R vizlab/make/log/fetch/iris-data.Rout
vizlab/make/timestamps/iris-data: iris-data_timestamp
iris-data_timestamp: 
	export R_LIBS_USER=$(RLIBSUSER);\
	${RBATCH} "--args fun=fetchTimestamp funargs=list(viz='iris-data')" \
	vizlab/make/callFunction.R vizlab/make/log/fetch/iris-data_timestamp.Rout
```

**Comment by aappling-usgs** [comment] 2017-09-13 00:04
Inching forward: for Irma `view-limits`, which was getting made anew every time (and causing `precip-data` to also get made every time):

- `refetch: TRUE` was implied by viz.defaults.yaml
- because all `refetch` does is determine whether a timestamp should be fetched, `fetchTimestamp(viz)` was getting called for `fetcher: view_limits`
- because `fetchTimestamp.view_limits` was not implemented, a warning was being given by the superclass method `fetchTimestamp.fetcher`...but the warning was given in vizlab/make/log/fetch/view-limits_timestamp.Rout, and (very reasonably) nobody was checking that file for warnings. and `fetchTimestamp.fetcher` doesn't write any files, so we passed through silently
- timestamp fetching is designed to run every time in the makefile; this is so that your computer knows when there have been upstream changes
- because the superclass method `fetchTimestamp.fetcher` doesn't write any files, the target `vizlab/make/timestamps/view-limits` never became a file and was therefore always treated as newer than cache/view-limits.rds
- because `view-limits` was chronically out of date relative to `timestamps/view-limits`, `cache/view-limits.rds` was getting made anew every time
- because `precip-data` depends on `cache/view-limits.rds`, `precip-data` was getting made every time

**Comment by aappling-usgs** [comment] 2017-09-13 01:35
Several possible solutions/salves to the `fetchTimestamp`:

1. Change the warning to an error in `fetchTimestamp.fetcher` so that if `refetch: TRUE` and yet there's no timestamp fetcher implemented, the user gets notified immediately. (This will break past vizzies unless/until their `refetch` arguments are all correct, so we should roll it out carefully.)
2. Remove/ignore the `refetch` argument. Instead, check during `createMakefiles` for the presence of a `fetchTimestamp` method for each viz.yaml item's fetcher. If no such method exists, we could assume `refetch: FALSE` and omit the timestamp check from the makefile. Is this a good idea? What if someone intended to implement `fetchTimestamp` but forgot? What if they forgot to list the timestamp-implementing script in `scripts` or misspelled the name? Will it be obvious to them that something is wrong?
3. Keep the `refetch` argument, but rename it to clear up what it does (back to `fetchTimestamp` or to something new?) and throw an error if both `refetch: TRUE` and no `fetchTimestamp.xx` method is found for the given fetcher during `createMakefiles` (after sourcing(is that safe?!) the `scripts:` for the given item). This will also break past vizzies, so again be careful.

Other issues:

1. Look into the behavior when `fetcher`=`file`, because `fetchTimestamp.file` does nothing, which should have the same annoying effect as the lack of fetchTimestamp implementation (see iris-data with refetch: TRUE in the USGS-VIZLAB/example repo). It should probably either (1) not be implemented, so we get the error as above, or (2) write the timestamp file. I prefer option 1.
2. While we're sensitive to the issue, check for other S3 generics in `vizlab` for which the superclass method gives a warning rather than an error. Is it OK for those warnings to disappear into log files, or does the user need to know about them?

**Comment by aappling-usgs** [comment] 2017-09-13 18:20
Settling in on this plan for `refetch`:
1. rename to `fetchTimestamp` (because `refetch` implies this argument is more powerful than it actually is, and doesn't make the connection to the fetchTimestamp method that the user may need to write)
2. throw an error if users have `fetchTimestamp: true` but there ISN'T a `fetchTimestamp` method for the designated fetcher (to avoid the case where users forget / don't know that they need to implement one, which causes `make` to remake the target every time)
3. create a message that gets displayed during `make` if `fetchTimestamp: false` but there IS a `fetchTimestamp` method (to reminder users to change it back before sending to Jenkins)

We could do a little better than (3) in the future, probably along with https://github.com/USGS-VIZLAB/vizlab/issues/102, by creating/permitting a user-specific file that lists the targets whose timestamps should not be refetched, or at least not for a while. This file would remain local (not git committed) to avoid the humans-Jenkins clash related to https://github.com/USGS-VIZLAB/vizlab/issues/192#issuecomment-328910176 (3). After this file handling was implemented, any mismatch between the viz.yaml flags and available methods for `fetchTimestamp` would generate an error. We could then consider taking out the `fetchTimestamp` argument entirely (for ease) or leaving it in (for clarity) - still not sure which would be better.

**Comment by aappling-usgs** [comment] 2017-09-13 20:52
Here's a table of scenarios and expected behavior if we implement the above plan. The example is for a viz item with id `cars-data`, `fetcher: cars`, `fetch.cars()` implemented in cars.R, and `fetchTimestamp.cars` either implemented or not in cars.R depending on scenario. This all assumes that `fetchTimestamp` is not referenced or used within the user's R code.

### Scenarios:

| `fetch Timestamp` | `fetch Timestamp. cars` | local timestamp | remote timestamp | code timestamp | on `create Makefiles()` | on `make -f vizlab/make/fetch.make cars-data` | 
| --- | --- | --- | --- | --- | --- | --- |
| `true` | exists | _missing_ | 8 am | 7 am | silent | downloads cars.csv |
| `true` | exists | 9 am | 8 am | 7 am | silent | checks remote, no download |
| `true` | exists | 9 am | 10 am | 7 am | silent | checks remote, downloads cars.csv |
| `true` | exists | 9 am | _any_ | 11 am | silent | checks remote (avoidable?), downloads cars.csv |
| `false` | missing | _missing_ | 8 am | 7 am | silent | downloads cars.csv |
| `false` | missing | 9 am | 8 am | 7 am | silent | no check, no download |
| `false` | missing | 9 am | 10 am | 7 am | silent | no check, no download |
| `false` | missing | 9 am | _any_ | 11 am | silent | no check, downloads cars.csv |
| `true` | missing | _any_ | _any_ | _any_ | error: `"missing timestamp fetcher for cars-data. either set 'refetch: FALSE' or implement fetchTimestamp.cars and list the .R file in 'scripts:'"` | NA |
| `false` | exists | _missing_ | _any_ | 7 am | silent | message: `"fetchTimestamp is false in viz.yaml but fetchTimestamp method is available; change before git commit"`, no check,  downloads cars.csv |
| `false` | exists | 9 am | _any_ | 7 am | silent | message: `"fetchTimestamp is false in viz.yaml but fetchTimestamp method is available; change before git commit"`, no check, no download |
| `false` | exists | 9 am | _any_ | 11 am | silent | message: `"fetchTimestamp is false in viz.yaml but fetchTimestamp method is available; change before git commit"`, no check, downloads cars.csv |

### Column definitions:

- `fetchTimestamp` = the value of the viz.yaml fetchTimestamp argument for the `cars-data` item
- `fetchTimestamp.cars` = 'exists' if `fetchTimestamp.cars` is implemented in cars.R, 'missing' otherwise
- local timestamp = timestamp on your computer's copy of cache/fetch/cars-data.csv (if `fetchTimestamp: false`) or timestamp on your computer's copy of vizlab/make/timestamps/cars-data (if `fetchTimestamp: true`). The two timestamps will be nearly identical at all times, so lumping in one column. '[missing]' if the data file doesn't exist.
- remote timestamp = The `dateUploaded` of the file on ScienceBase. If this value differs from the _contents_ of vizlab/make/timestamps/cars-data, when `fetchTimestamp: true` and assuming fetchTimestamp.sciencebase is implemented correctly, then vizlab/make/timestamps/cars-datawill be updated and that will cause your computer to download the modified data to cache/fetch/cars-data.csv.
- code timestamp = The maximum (latest) timestamp on cache/config/cars-data.rds and scripts/fetch/cars.R, where cache/config/cars-data.rds is updated if the viz.yaml block for `cars-data` is edited
- on `createMakefiles()` = what happens when you call `createMakefile()` or `make fetch`
- on `make -f vizlab/make/fetch.make Cuyahoga` = what happens when you call `make -f vizlab/make/fetch.make Cuyahoga` (after calling `createMakefile()` or `make fetch`)

**Comment by aappling-usgs** [comment] 2017-09-14 15:03
Questions:
1. Should scenarios 10-12 produce a message or an error?
2. Should there even be a `fetchTimestamp` flag, or should we simply infer it from the presence or absence of a fetchTimestamp.myfetcher method?
3. Especially if answer to 1 is error or answer to 2 is infer, should we go ahead and implement that local-configuration solution, maybe with time to live (where the ~equivalent of refetch=FALSE would be timetolive=Inf)? Maybe a file called `preferences.yml` in the main directory, with a subsection for `timetolive`?

**Comment by aappling-usgs** [comment] 2017-09-14 16:38
New proposal for scenarios and behavior. The example is for a viz item with id `cars-data`, `fetcher: cars`, `fetch.cars()` implemented in cars.R, and `fetchTimestamp.cars` either implemented or not in cars.R depending on scenario. In this proposal we're removing `viz$refetch` and `viz$fetchTimestamp` entirely, and `create Makefiles()` is always silent.

### Scenarios:

| `fetch Timestamp. cars` | local timestamp | remote timestamp | code timestamp | on `make -f vizlab/make/fetch.make cars-data` | 
| --- | --- | --- | --- | --- |
| exists | _missing_ | 8 am | 7 am | downloads cars.csv |
| exists | 9 am | 8 am | 7 am | checks remote, no download |
| exists | 9 am | 10 am | 7 am | checks remote, downloads cars.csv |
| exists | 9 am | _any_ | 11 am | checks remote (avoidable?), downloads cars.csv |
| missing | _missing_ | 8 am | 7 am | downloads cars.csv |
| missing | 9 am | 8 am | 7 am | no check, no download |
| missing | 9 am | 10 am | 7 am | no check, no download |
| missing | 9 am | _any_ | 11 am |no check, downloads cars.csv |

### Column definitions:

- `fetchTimestamp.cars` = 'exists' if `fetchTimestamp.cars` is implemented in cars.R, 'missing' otherwise
- local timestamp = timestamp on your computer's copy of cache/fetch/cars-data.csv (if `fetchTimestamp: false`) or timestamp on your computer's copy of vizlab/make/timestamps/cars-data (if `fetchTimestamp: true`). The two timestamps will be nearly identical at all times, so lumping in one column. '[missing]' if the data file doesn't exist.
- remote timestamp = The `dateUploaded` of the file on ScienceBase. If this value differs from the _contents_ of vizlab/make/timestamps/cars-data, when `fetchTimestamp: true` and assuming fetchTimestamp.sciencebase is implemented correctly, then vizlab/make/timestamps/cars-datawill be updated and that will cause your computer to download the modified data to cache/fetch/cars-data.csv.
- code timestamp = The maximum (latest) timestamp on cache/config/cars-data.rds and scripts/fetch/cars.R, where cache/config/cars-data.rds is updated if the viz.yaml block for `cars-data` is edited
- on `make -f vizlab/make/fetch.make cars-data` = what happens when you call `make -f vizlab/make/fetch.make cars-data` (after calling `createMakefile()` or `make fetch`)

**Comment by ldecicco-USGS** [comment] 2017-09-14 17:53
(sigh...never hit "Comment")

1. Hmm...I would have voted message, because maybe there are instances where the user wanted to set it false on purpose.
2. Inferring would be good I guess. I guess this completely depends on if we can think of a reason for the user to set to false.
3. You're selling me on this as I type...also leaning towards yes.

**Comment by aappling-usgs** [comment] 2017-09-14 18:27
feedback:
JIW:
* fetchTimestamp flag is still pretty confusing, now also not very helpful. take out this check
* in the example project, write a fetcher with fetch and fetchTimestamp. The easy implementation is fetchTimestamp.precipdata = fetchTimestamp.file, which of course is in appropriate if there is actually a remote file. mention fetchTimestamp.sciencebase as example for a remote that changes
* always require a fetcher to have a fetchTimestamp method (but AA wants to check whether fetchTimestamp.file is really working as expected)
LDC: 
* yes, go ahead, and do implement/demonstrate the workaround

**Comment by aappling-usgs** [comment] 2017-09-15 04:58
New new proposal for scenarios and behavior, summarizing above feedback. The example is for a viz item with id `cars-data`, `fetcher: cars`, `fetch.cars` implemented in cars.R, and `fetchTimestamp.cars` either implemented or not in cars.R depending on scenario. In this proposal we're ignoring `viz$refetch` entirely, `viz$fetchTimestamp` is optional and limited in scope, and `createMakefiles()` is always silent unless `viz$fetchTimestamp` exists.

* we now require a `fetchTimestamp.xxx` method to be implemented and depended on for every fetcher `xxx`. these methods should actually write a timestamp file at least once; this is facilitated by a slightly easier-to-use `writeTimestamp` function, and is now implemented for the built-in `fetchTimestamp.file` method.
* there is no `fetchTimestamp` or `refetch` flag in the viz.yaml anymore. to discourage this, we give errors when either flag is used. we could ease up on this when everybody is used to the idea in a year or two.
* i'm working on an example in the `USGS-VIZLAB/example` repo for a custom method `fetchTimestamp.cars`.

### Scenarios:

| `fetch Timestamp. cars` | timetolive | local timestamp | remote timestamp | code timestamp | on `make -f vizlab/make/fetch.make cars-data` | 
| --- | --- | --- | --- | --- | --- |
| exists | _any_ | _missing_ | _any_ | _any_ | downloads cars.csv |
| exists | "0 secs" | 9 am | 8 am | 7 am | checks remote, no download |
| exists | "0 secs" | 9 am | 10 am | 7 am | checks remote, downloads cars.csv |
| exists | "0 secs" | 9 am | 8 am | 11 am | checks remote (avoidable?), downloads cars.csv |
| exists | "30 mins" | 9 am | 8 am | 7 am | checks remote, no download |
| exists | "Inf days" | 9 am | 8 am | 7 am | no check, no download |
| exists | "Inf days" | 9 am | 8 am | 11 am | no check, downloads cars.csv |

### Column definitions:

- `fetchTimestamp.cars` = 'exists' if `fetchTimestamp.cars` is implemented in cars.R, 'missing' otherwise
- timetolive = preference for this viz item in preferences.yaml in the `timetolive` block (default of "0 secs"): how long should we wait since the last download before checking the timestamp again?
- local timestamp = timestamp on your computer's copy of cache/fetch/cars-data.csv (if `fetchTimestamp: false`) or timestamp on your computer's copy of vizlab/make/timestamps/cars-data (if `fetchTimestamp: true`). The two timestamps will be nearly identical at all times, so lumping in one column. '[missing]' if the data file doesn't exist.
- remote timestamp = The `dateUploaded` of the file on ScienceBase. If this value differs from the _contents_ of vizlab/make/timestamps/cars-data, when `fetchTimestamp: true` and assuming fetchTimestamp.sciencebase is implemented correctly, then vizlab/make/timestamps/cars-datawill be updated and that will cause your computer to download the modified data to cache/fetch/cars-data.csv.
- code timestamp = The maximum (latest) timestamp on cache/config/cars-data.rds and scripts/fetch/cars.R, where cache/config/cars-data.rds is updated if the viz.yaml block for `cars-data` is edited
- on `make -f vizlab/make/fetch.make cars-data` = what happens when you call `make -f vizlab/make/fetch.make cars-data` (after calling `createMakefile()` or `make fetch`)

**Comment by aappling-usgs** [comment] 2017-09-15 15:35
this issue now includes https://github.com/USGS-VIZLAB/vizlab/issues/102 as part of the MVP

**Closed** 2017-09-15 21:44 UTC

**Comment by aappling-usgs** [comment] 2017-09-17 20:46
@jread-usgs = Re: comment linked above from #207:

I believe that problem falls under this issue, #192, because a quick application of the new vizlab 0.2.x to hurricane-irma gives this:
```
> library(vizlab)
> createMakefiles()
Error in needsTimestamp(item.info) : 
  fetchTimestamp.view_limits must be implemented for view-limits, probably in an R file in 'scripts:'
```
bringing us back to https://github.com/USGS-VIZLAB/vizlab/issues/192#issuecomment-329018673, where we established that view_limits is getting rebuilt every time because fetchTimestamp.view_limits is unimplemented, so the timestamp file never gets created, so the data file appears to be always out of date relative to that infinitely new timestamp file. view_limits is a dependency of all three of counties, states, and islands, so when view_limits is rebuilt, those spatial objects are (and should be) rebuilt.

When I run `devtools::install_github("USGS-VIZLAB/vizlab@v0.1.8.10")` and `make states` (roughly), I can reproduce the problem you described. I see the same 4 retries every time, for `states_timestamp`, `view-limits_timestamp`, `cache/view-limits.rds`, and `cache/states.rds`:
```
$ make -f vizlab/make/fetch.make cache/states.rds
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetchTimestamp funargs=list(viz='states') scripts=c('scripts/fetch/fetch.states.R','scripts/visua
lize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/states_timestamp.Rout
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetchTimestamp funargs=list(viz='view-limits') scripts=c('scripts/fetch/fetch.view_limits.R','scr
ipts/visualize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/view-limits_timestamp.Rout
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetch funargs=list(viz='view-limits') scripts=c('scripts/fetch/fetch.view_limits.R','scripts/visu
alize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/view-limits.Rout
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetch funargs=list(viz='states') scripts=c('scripts/fetch/fetch.states.R','scripts/visualize/visu
alize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/states.Rout
```
which confirms that everything is getting rebuilt every time.

## with vizlab 0.2.x

When I run `devtools::install_github("USGS-VIZLAB/vizlab@0.2.x")` (commit 845476c) and then `createMakefiles()` I get the error at the top of this comment. I address that one, and the several that follow, like this:

I edit fetch.view_limits.R by adding these lines:
```r
fetchTimestamp.view_limits <- vizlab:::fetchTimestamp.file
fetchTimestamp.storm_area_filter <- vizlab:::fetchTimestamp.file
```

and add these lines to fetch.states.R:
```r
fetchTimestamp.states <- vizlab:::fetchTimestamp.file
fetchTimestamp.counties <- vizlab:::fetchTimestamp.file
fetchTimestamp.islands <- vizlab:::fetchTimestamp.file
```

and then add similar lines for hurricaneTrack, precipSpatial, precipCellData, sites, nws_conversion, nws_data, timesteps, and nwis_data.

I haven't thought deeply through whether `fetchTimestamp.file` is uniformly the right choice for all of these fetch items, but I think it will get us started. (side note: just opened https://github.com/USGS-VIZLAB/vizlab/issues/221 to expose `vizlab:::fetchTimestamp.file` and think harder about it.)

Next I remove all instances of `refetch:` in viz.yaml. Now `createMakefiles()` finally runs, and the next call to `make states` builds everything including timestamps, and subsequent calls only check timestamps. Just like we want.

```r
$ make -f vizlab/make/fetch.make cache/states.rds
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetchTimestamp funargs=list(viz='states') scripts=c('scripts/fetch/fetch.states.R','scripts/visua
lize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/states_timestamp.Rout
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetchTimestamp funargs=list(viz='view-limits') scripts=c('scripts/fetch/fetch.view_limits.R','scr
ipts/visualize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/view-limits_timestamp.Rout
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/Rscript.exe --quiet --no-save --no-restore  -e "library(vizlab); upd
ateConfigInfoFile('view-limits')"\
> vizlab/make/log/config.Rout 2>&1
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetch funargs=list(viz='view-limits') scripts=c('scripts/fetch/fetch.view_limits.R','scripts/visu
alize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/view-limits.Rout
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/Rscript.exe --quiet --no-save --no-restore  -e "library(vizlab); upd
ateConfigInfoFile('states')"\
> vizlab/make/log/config.Rout 2>&1
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetch funargs=list(viz='states') scripts=c('scripts/fetch/fetch.states.R','scripts/visualize/visu
alize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/states.Rout

$ make -f vizlab/make/fetch.make cache/states.rds
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetchTimestamp funargs=list(viz='states') scripts=c('scripts/fetch/fetch.states.R','scripts/visua
lize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/states_timestamp.Rout
export R_LIBS_USER=C:/Users/a/Documents/R/win-library/3.4;\
C:/Program\ Files/R/R-3.4.1/bin/R.exe CMD BATCH --no-timing --quiet --no-save --no-restore "--args f
un=fetchTimestamp funargs=list(viz='view-limits') scripts=c('scripts/fetch/fetch.view_limits.R','scr
ipts/visualize/visualize_utils.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/view-limits_timestamp.Rout
```

At this point I believe the problem is solved. I can also re-install USGS-VIZLAB/vizlab@v0.1.8.10, re-run createMakefiles(), and re-run `make -f vizlab/make/fetch.make cache/states.rds` with the file edits described above. Again, only the two fetchTimestamp calls are made, and the timestamp files already exist and are not created again, so neither `view-limits` nor `states` is rebuilt.

The changes I described above for Irma are at https://github.com/USGS-VIZLAB/hurricane-irma/pull/178. These edits should not be merged, because I Irma includes 5 instances of code that does things with the `refetch` fields from the viz.yaml, and now I've deleted those. And `fetchTimestamp.file` is not the appropriate fetcher for remote data that is expected to change. So even though the `make` flow is improved, the overall system is likely broken in some different way.
